### PR TITLE
Fixing support for multiple select query params

### PR DESCRIPTION
**Pull request by xamien**

### CODE REVIEW

**Comment by xamien** [comment]
On more fix for query select...

**Comment by travist** [comment]
This breaks reverse compatibility... we used to allow a "comma separated" list of items. Is that now broken with this?

**Comment by xamien** [comment]
I don't think so. This is only for select query param and it seems to behaving well, even the tests are passing. Should I write a specific test?

**Comment by travist** [comment]
Yep, looks good.  Thanks.

**Pull request merged**
