### PR TITLE
Added 'Virtual Resources' section to the readme file

### PR DESCRIPTION
**Pull request by biofractal**
see #17 readme: virtual resources

Added a new section to the readme doc to explain the virtual resources feature

### CODE REVIEW

**Comment by zackurben** [comment]
Hey man, thanks for adding to the readme! Any chance you can squash these commits?

**Comment by biofractal** [comment]
Um .. OK, maybe messed things up, maybe not. Not to sure. I went a bit git-crazy and just squashed the last 35 commits but I think maybe I might have over-squashed.

**Comment by travist** [comment]
Oh man... I actually think the ground shifted beneath your feet a little and it messed up your commits. What I would do if I were you is just create a new branch based off of ```origin/master```, manually copy and paste your documentation changes, create a single fresh commit, and then push up that custom branch and do the pull request against it.  That way it will be clean and you won't get into rebase hell like you apparently were in.

**Comment by biofractal** [comment]
Done. Deleted old fork and took a clean one from your master. Added the block of text in one go and created a new pull request.

**Pull request closed without merging**
