### PR TITLE
Coveralls, Virtual Improvements, Removal of Lodash and Middleware in favor of ES6 and EspressJS

### PR DESCRIPTION
**Pull request by Sefriol**
Release Candidate (Updated):
- Coveralls support
- Some fixes to testing
- Some eslint errors resolved
- Improve Travis configuration (mongo setup, addition and removal of node versions)
- Dependancy updates
- Switch composable-middleware to native ExpessJS (NEW)
- skipResource tests, some error and empty query error tests, patch tests (NEW)
- Tests for Virtual (NEW)
- Tests that virtual paths are NOT defined when there is no virtual resources available (NEW, Done via Swagger)
- Removal of lodash in favor of ES6

Possible:
- Add test for untested [parts](https://coveralls.io/github/Sefriol/resourcejs) (~~skipResource~~, ~~incorrect patch~~, writeOptions error, convertIds, index query error)

### CODE REVIEW

**Comment by travist** [comment]
Looks good! Thank you!

I will find some time to really kick the tires on this one as soon as I create a new build of Form.io

**Comment by travist** [comment]
I'm just curious what your motivation was to remove Lodash? I had to fix many bugs and most of them were due to the removal of Lodash and replacing those with hand-baked methods that were not equivalent.... like ```mapValues``` and replacing ```_.isEmpty``` with ```.length !== 0``` (which only works if the item was array which in this case was not causing a bug).

Is your concern with size?  Performance?  We could import the methods directly if your concern is size like ```import isEmpty from 'lodash/isEmpty'``` but this is only something you would do if you were building a front end library and not a backend node.js server. 

I am just curious what your thoughts are on this. Overall, I do like the change, but did run into some issues when trying to implement them with our other dependencies we have at Form.io.

**Comment by Sefriol** [comment]
In general I just thought that the use of lodash was so minimal that it was not a necessary import anymore when ES6 was under support of all active nodejs versions. Lodash has had it's problems with performance, size and security. I thought it would be natural change to just pace it out, but it's just my opinion.

Some of the implementations probably needed more fine tuned testing, since not all of them have exactly the same implementation in ES6. That was the part where I wanted your input on the matter since I was not sure whether the current tests had enough coverage to take into account all of the possible use cases (btw, coverage uses a link to my repository, so it would be a good idea to change).

I'm also in favor of less dependancies, the better. Especially on packages which try to implement certain features for the backend. (One of the reasons why I removed composable-middleware. I tried to keep only essential things that are too complex to implement on your own. In addition on some of them being quite outdated, even though functional) 

But as said, I did not intend this to go straight to master as it is. I thought it might need more fine tuning. :)

**Comment by travist** [comment]
It's not a problem. I did have to make some changes to get all the tests in formio/formio passing (there are a bunch there), so 2.0.2 should be good and also reverse compatible.

**Pull request merged**
